# rename me to config.yml
# see https://github.com/benprew/pony
smtp:
  address: "smtp.gmail.com"
  port: "587"
  enable_starttls_auto: true
  user_name: username
  password: password
  authentication: :plain
